name: Create an issue
description: Creates a new issue using a template with front matter.
runs:
  using: docker
  image: Dockerfile
branding:
  icon: alert-circle
  color: gray-dark
inputs:
  assignees:
    description: GitHub handle of the user(s) to assign the issue (comma-separated)
  milestone:
    description: Number of the milestone to assign the issue to
    required: false
  filename:
    description: The name of the file to use as the issue template
    default: .github/ISSUE_TEMPLATE.md
  reportFilesPattern :
    description: absolute path pattern to report JSON files
    default: ./anchore-reports/scan_*.json
outputs:
  number:
    description: Number of the issue that was created
  url:
    description: URL of the issue that was created
